services:
  - type: web
    name: atheeg-api
    env: node
    rootDir: .
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://your-vercel-frontend-url.vercel.app
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
