import { jsPDF } from 'jspdf';
import { Attempt, Test } from '../types';

export function generateCandidateResultPDF(attempt: Attempt, test?: Test | null): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Background tint
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, 210, 297, 'F');

  // Header banner
  doc.setFillColor(30, 41, 59);
  doc.roundedRect(12, 12, 186, 36, 3, 3, 'F');

  // Brand Logo Accent
  doc.setFillColor(99, 102, 241);
  doc.circle(28, 30, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('A', 26, 34);

  // Title
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text('ATHEEG TEST — OFFICIAL SCORECARD', 44, 28);

  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('Master Every Test. Ace Every Exam. | Verified Client Examination Certificate', 44, 36);

  // Candidate info box
  doc.setFillColor(19, 24, 41);
  doc.roundedRect(12, 54, 186, 40, 3, 3, 'F');
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.3);
  doc.roundedRect(12, 54, 186, 40, 3, 3, 'S');

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text('Candidate Name:', 18, 64);
  doc.text('Candidate Email:', 18, 72);
  doc.text('Test Assessment:', 18, 80);
  doc.text('Test Code:', 18, 88);

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text(attempt.candidateName, 55, 64);
  doc.text(attempt.candidateEmail, 55, 72);
  doc.text(attempt.testTitle, 55, 80);
  doc.text(attempt.testCode, 55, 88);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('Date Completed:', 115, 64);
  doc.text('Time Spent:', 115, 72);
  doc.text('Exam Status:', 115, 80);
  doc.text('Proctoring Audit:', 115, 88);

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  const dateStr = new Date(attempt.submittedAt).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  doc.text(dateStr, 150, 64);
  doc.text(`${Math.floor(attempt.timeTaken / 60)}m ${attempt.timeTaken % 60}s`, 150, 72);
  doc.setTextColor(attempt.percentage >= 60 ? 34 : 239, attempt.percentage >= 60 ? 197 : 68, attempt.percentage >= 60 ? 94 : 68);
  doc.text(attempt.percentage >= 60 ? 'PASSED (PASS)' : 'RETAKE SUGGESTED', 150, 80);
  doc.setTextColor(attempt.proctoringEventsCount === 0 ? 34 : 245, 197, 94);
  doc.text(attempt.proctoringEventsCount === 0 ? 'Clean (0 events)' : `${attempt.proctoringEventsCount} alerts logged`, 150, 88);

  // Score Summary Banner
  doc.setFillColor(30, 41, 59);
  doc.roundedRect(12, 100, 186, 30, 3, 3, 'F');

  doc.setFontSize(11);
  doc.setTextColor(148, 163, 184);
  doc.text('OVERALL SCORE', 25, 110);
  doc.text('PERCENTAGE', 75, 110);
  doc.text('QUESTIONS ANSWERED', 125, 110);

  doc.setFontSize(16);
  doc.setTextColor(34, 211, 238);
  doc.setFont('helvetica', 'bold');
  doc.text(`${attempt.score} / ${attempt.totalQuestions}`, 25, 122);
  doc.text(`${attempt.percentage}%`, 75, 122);
  const answeredCount = Object.values(attempt.answers).filter(v => v !== null).length;
  doc.text(`${answeredCount} of ${attempt.totalQuestions}`, 125, 122);

  // Level Breakdown
  let y = 142;
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text('Level-wise Performance Breakdown', 14, y);
  y += 6;

  doc.setFillColor(19, 24, 41);
  doc.rect(12, y, 186, 8, 'F');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'bold');
  doc.text('LEVEL NAME', 16, y + 5.5);
  doc.text('TOTAL QUESTIONS', 100, y + 5.5);
  doc.text('CORRECT', 145, y + 5.5);
  doc.text('ACCURACY', 175, y + 5.5);
  y += 9;

  attempt.levelScores.forEach((lvl, i) => {
    doc.setFillColor(i % 2 === 0 ? 25 : 30, i % 2 === 0 ? 33 : 41, i % 2 === 0 ? 50 : 59);
    doc.rect(12, y, 186, 9, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(255, 255, 255);
    doc.text(lvl.levelName, 16, y + 6);
    doc.text(lvl.totalQuestions.toString(), 105, y + 6);
    doc.text(lvl.correctAnswers.toString(), 150, y + 6);
    const lvlPct = Math.round((lvl.correctAnswers / (lvl.totalQuestions || 1)) * 100);
    doc.text(`${lvlPct}%`, 178, y + 6);
    y += 10;
  });

  // Footer certificate notice
  y = 265;
  doc.setDrawColor(51, 65, 85);
  doc.line(12, y, 198, y);
  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text('This document is an electronic validation certificate generated by Atheeg Test Platform.', 14, y);
  doc.text(`Certificate ID: ${attempt.id} | Generated at ${new Date().toISOString()}`, 14, y + 5);

  doc.save(`Atheeg-Test-Result-${attempt.testCode}-${attempt.candidateName.replace(/\s+/g, '_')}.pdf`);
}

export function exportAttemptsToCSV(attempts: Attempt[]): void {
  const headers = ['Attempt ID', 'Candidate Name', 'Candidate Email', 'Test Title', 'Test Code', 'Score', 'Total Questions', 'Percentage', 'Time Taken (s)', 'Status', 'Proctoring Events', 'Submitted At'];
  const rows = attempts.map(a => [
    `"${a.id}"`,
    `"${a.candidateName.replace(/"/g, '""')}"`,
    `"${a.candidateEmail}"`,
    `"${a.testTitle.replace(/"/g, '""')}"`,
    `"${a.testCode}"`,
    a.score,
    a.totalQuestions,
    `${a.percentage}%`,
    a.timeTaken,
    `"${a.status}"`,
    a.proctoringEventsCount,
    `"${a.submittedAt}"`
  ]);

  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `atheeg-attempts-${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
